
import cats.{Applicative, Monoid, Monad}
import cats.implicits._
import ltbs.uniform._

import language.implicitConversions


package programs {
  case class DataType1(i: String)
  case class DataType2(i: String)
  case class DataType3(i: String)
  case class DataType4(i: String)
  case class DataType5(i: String)
  case class DataType6(i: String)
  case class DataType7(i: String)
  case class DataType8(i: String)
  case class DataType9(i: String)
  case class DataType10(i: String)
  case class DataType11(i: String)
  case class DataType12(i: String)
  case class DataType13(i: String)
  case class DataType14(i: String)
  case class DataType15(i: String)
  case class DataType16(i: String)
  case class DataType17(i: String)
  case class DataType18(i: String)
  case class DataType19(i: String)
  case class DataType20(i: String)
  case class DataType21(i: String)
  case class DataType22(i: String)
  case class DataType23(i: String)
  case class DataType24(i: String)
  case class DataType25(i: String)
  case class DataType26(i: String)
  case class DataType27(i: String)
  case class DataType28(i: String)
  case class DataType29(i: String)
  case class DataType30(i: String)
  case class DataType31(i: String)
  case class DataType32(i: String)
  case class DataType33(i: String)
  case class DataType34(i: String)
  case class DataType35(i: String)
  case class DataType36(i: String)
  case class DataType37(i: String)
  case class DataType38(i: String)
  case class DataType39(i: String)
  case class DataType40(i: String)
  case class DataType41(i: String)
  case class DataType42(i: String)
  case class DataType43(i: String)
  case class DataType44(i: String)
  case class DataType45(i: String)
  case class DataType46(i: String)
  case class DataType47(i: String)
  case class DataType48(i: String)
  case class DataType49(i: String)
  case class DataType50(i: String)
  case class DataType51(i: String)
  case class DataType52(i: String)
  case class DataType53(i: String)
  case class DataType54(i: String)
  case class DataType55(i: String)
  case class DataType56(i: String)
  case class DataType57(i: String)
  case class DataType58(i: String)
  case class DataType59(i: String)
  case class DataType60(i: String)
  case class DataType61(i: String)
  case class DataType62(i: String)
  case class DataType63(i: String)
  case class DataType64(i: String)
  case class DataType65(i: String)
  case class DataType66(i: String)
  case class DataType67(i: String)
  case class DataType68(i: String)
  case class DataType69(i: String)
  case class DataType70(i: String)
  case class DataType71(i: String)
  case class DataType72(i: String)
  case class DataType73(i: String)
  case class DataType74(i: String)
  case class DataType75(i: String)
  case class DataType76(i: String)
  case class DataType77(i: String)
  case class DataType78(i: String)
  case class DataType79(i: String)
  case class DataType80(i: String)
  case class DataType81(i: String)
  case class DataType82(i: String)
  case class DataType83(i: String)
  case class DataType84(i: String)
  case class DataType85(i: String)
  case class DataType86(i: String)
  case class DataType87(i: String)
  case class DataType88(i: String)
  case class DataType89(i: String)
  case class DataType90(i: String)
  case class DataType91(i: String)
  case class DataType92(i: String)
  case class DataType93(i: String)
  case class DataType94(i: String)
  case class DataType95(i: String)
  case class DataType96(i: String)
  case class DataType97(i: String)
  case class DataType98(i: String)
  case class DataType99(i: String)
  case class DataType100(i: String)
}

package object programs {


  type TellTypes = NilTypes
  type AskTypes = (Int, Int) :: Int :: Boolean :: NilTypes

  def greasy[F[_] : Monad](
    interpreter: Language[F, TellTypes, AskTypes]
  ): F[Int] = {
    import interpreter._
    for {
      age           <- ask[Int]("age")
      h2            <- ask[(Int,Int)]("height")
      height3       <- ask[Int]("height3")                  
      food          <- ask[Boolean]("wantFood")
      tea           <- ask[Boolean]("wantTea")
      baconCost     <- ask[Int]("bacon").map(_ * 12) emptyUnless food
      eggsCost      <- ask[Int]("eggs").map(_ * 24) emptyUnless food
      foodCost      = baconCost + eggsCost
      teaCost       <- ask[Int]("sugar").map(_ * 10 + 50) emptyUnless tea
      youngDiscount = if (age < 16) teaCost / 10 else 0
      oldDiscount   = if (age > 60) (teaCost + foodCost) * (Math.min(age - 60,25) / 100) else 0
    } yield (foodCost + teaCost + youngDiscount + oldDiscount)
  }

  type TellTypes2 = NilTypes
  type AskTypes2 = DataType1 :: DataType2 :: DataType3 :: DataType4 :: DataType5 :: DataType6 :: DataType7 :: DataType8 :: DataType9 :: DataType10 :: DataType11 :: DataType12 :: DataType13 :: DataType14 :: DataType15 :: DataType16 :: DataType17 :: DataType18 :: DataType19 :: DataType20 :: DataType21 :: DataType22 :: DataType23 :: DataType24 :: DataType25 :: DataType26 :: DataType27 :: DataType28 :: DataType29 :: DataType30 :: DataType31 :: DataType32 :: DataType33 :: DataType34 :: DataType35 :: DataType36 :: DataType37 :: DataType38 :: DataType39 :: DataType40 :: DataType41 :: DataType42 :: DataType43 :: DataType44 :: DataType45 :: DataType46 :: DataType47 :: DataType48 :: DataType49 :: DataType50 :: DataType51 :: DataType52 :: DataType53 :: DataType54 :: DataType55 :: DataType56 :: DataType57 :: DataType58 :: DataType59 :: DataType60 :: DataType61 :: DataType62 :: DataType63 :: DataType64 :: DataType65 :: DataType66 :: DataType67 :: DataType68 :: DataType69 :: DataType70 :: DataType71 :: DataType72 :: DataType73 :: DataType74 :: DataType75 :: DataType76 :: DataType77 :: DataType78 :: DataType79 :: DataType80 :: DataType81 :: DataType82 :: DataType83 :: DataType84 :: DataType85 :: DataType86 :: DataType87 :: DataType88 :: DataType89 :: DataType90 :: DataType91 :: DataType92 :: DataType93 :: DataType94 :: DataType95 :: DataType96 :: DataType97 :: DataType98 :: DataType99 :: DataType100 :: NilTypes

  def crazyTypesProgram[F[_]: Monad](
    interpreter: Language[F, TellTypes2, AskTypes2]
  ): F[Unit] = {
    import interpreter._
    for {
      _   <- ask[DataType1]("one")
      _   <- ask[DataType2]("two")
      _   <- ask[DataType3]("three")
      _   <- ask[DataType4]("four")
      _   <- ask[DataType5]("five")
      _   <- ask[DataType6]("six")
      _   <- ask[DataType7]("seven")
      _   <- ask[DataType8]("eight")
      _   <- ask[DataType9]("nine")
      _   <- ask[DataType10]("ten")
      _   <- ask[DataType11]("eleven")
      _   <- ask[DataType12]("twelve")
      _   <- ask[DataType13]("thirteen")
      _   <- ask[DataType14]("fourteen")
      _   <- ask[DataType15]("fifteen")
      _   <- ask[DataType16]("sixteen")
      _   <- ask[DataType17]("seventeen")
      _   <- ask[DataType18]("eighteen")
      _   <- ask[DataType19]("nineteen")
      _   <- ask[DataType20]("twenty")
      _   <- ask[DataType21]("twenty-one")
      _   <- ask[DataType22]("twenty-two")
      _   <- ask[DataType23]("twenty-three")
      _   <- ask[DataType24]("twenty-four")
      _   <- ask[DataType25]("twenty-five")
      _   <- ask[DataType26]("twenty-six")
      _   <- ask[DataType27]("twenty-seven")
      _   <- ask[DataType28]("twenty-eight")
      _   <- ask[DataType29]("twenty-nine")
      _   <- ask[DataType30]("thirty")
      _   <- ask[DataType31]("thirty-one")
      _   <- ask[DataType32]("thirty-two")
      _   <- ask[DataType33]("thirty-three")
      _   <- ask[DataType34]("thirty-four")
      _   <- ask[DataType35]("thirty-five")
      _   <- ask[DataType36]("thirty-six")
      _   <- ask[DataType37]("thirty-seven")
      _   <- ask[DataType38]("thirty-eight")
      _   <- ask[DataType39]("thirty-nine")
      _   <- ask[DataType40]("forty")
      _   <- ask[DataType41]("forty-one")
      _   <- ask[DataType42]("forty-two")
      _   <- ask[DataType43]("forty-three")
      _   <- ask[DataType44]("forty-four")
      _   <- ask[DataType45]("forty-five")
      _   <- ask[DataType46]("forty-six")
      _   <- ask[DataType47]("forty-seven")
      _   <- ask[DataType48]("forty-eight")
      _   <- ask[DataType49]("forty-nine")
      _   <- ask[DataType50]("fifty")
      _   <- ask[DataType51]("fifty-one")
      _   <- ask[DataType52]("fifty-two")
      _   <- ask[DataType53]("fifty-three")
      _   <- ask[DataType54]("fifty-four")
      _   <- ask[DataType55]("fifty-five")
      _   <- ask[DataType56]("fifty-six")
      _   <- ask[DataType57]("fifty-seven")
      _   <- ask[DataType58]("fifty-eight")
      _   <- ask[DataType59]("fifty-nine")
      _   <- ask[DataType60]("sixty")
      _   <- ask[DataType61]("sixty-one")
      _   <- ask[DataType62]("sixty-two")
      _   <- ask[DataType63]("sixty-three")
      _   <- ask[DataType64]("sixty-four")
      _   <- ask[DataType65]("sixty-five")
      _   <- ask[DataType66]("sixty-six")
      _   <- ask[DataType67]("sixty-seven")
      _   <- ask[DataType68]("sixty-eight")
      _   <- ask[DataType69]("sixty-nine")
      _   <- ask[DataType70]("seventy")
      _   <- ask[DataType71]("seventy-one")
      _   <- ask[DataType72]("seventy-two")
      _   <- ask[DataType73]("seventy-three")
      _   <- ask[DataType74]("seventy-four")
      _   <- ask[DataType75]("seventy-five")
      _   <- ask[DataType76]("seventy-six")
      _   <- ask[DataType77]("seventy-seven")
      _   <- ask[DataType78]("seventy-eight")
      _   <- ask[DataType79]("seventy-nine")
      _   <- ask[DataType80]("eighty")
      _   <- ask[DataType81]("eighty-one")
      _   <- ask[DataType82]("eighty-two")
      _   <- ask[DataType83]("eighty-three")
      _   <- ask[DataType84]("eighty-four")
      _   <- ask[DataType85]("eighty-five")
      _   <- ask[DataType86]("eighty-six")
      _   <- ask[DataType87]("eighty-seven")
      _   <- ask[DataType88]("eighty-eight")
      _   <- ask[DataType89]("eighty-nine")
      _   <- ask[DataType90]("ninety")
      _   <- ask[DataType91]("ninety-one")
      _   <- ask[DataType92]("ninety-two")
      _   <- ask[DataType93]("ninety-three")
      _   <- ask[DataType94]("ninety-four")
      _   <- ask[DataType95]("ninety-five")
      _   <- ask[DataType96]("ninety-six")
      _   <- ask[DataType97]("ninety-seven")
      _   <- ask[DataType98]("ninety-eight")
      _   <- ask[DataType99]("ninety-nine")
      _   <- ask[DataType100]("one-hundred")
    } yield (())
  }

}
